[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "www_Day_Dream"
name = "Network_Behaviour_Event_Injector"
description = "A preload patcher that injects virtual NetworkBehaviour methods on all sub-classes."
websiteUrl = "https://github.com/www-Day-Dream/Daydream.NetworkBehaviourEvents"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../dist/"

[[build.copy]]
source  = "../Daydream.NetworkBehaviourEvents/bin/Release/Daydream.NetworkBehaviourEvents.dll"
target = "/BepInEx/patchers/Daydream.NetworkBehaviourEvents.dll"

[[build.copy]]
source = "../LICENSE.txt"
target = "LICENSE.txt"


[publish]
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["bepinex", "libraries", "tools"]